### ISSUE TITLE
Sidebar folder icon color problem with Sublime Text build 4095 

### ISSUE THREAD

**Issue by Jax0rz** [Monokai/monokai-pro-sublime-text#136]
<img width="1008" alt="CleanShot 2021-01-22 at 21 41 05@2x" src="https://user-images.githubusercontent.com/7557357/105497975-8c476280-5cfa-11eb-81ae-8b624d825d53.png">

**Comment by tempertemper** [comment]
+1 on this issue for me. I've been using Monokai Pro for ages and love it (I own both the ST and VSCode licenses), but is a real issue for me as my sidebar is darker than Jax0rz's so I can't tell what's a file and what's a folder 😞

I could turn on file icons so that there's a clearer distinction, but I find them distracting and untidy.

<img width="410" alt="Sublime text tree showing black arrows on a dark grey background" src="https://user-images.githubusercontent.com/2418781/105574430-6b175e00-5d5c-11eb-997d-5f6b2b3c2832.png">

**Comment by desilinguist** [comment]
Same here! I absolutely love Monokai Pro icons but not being able to tell what's a folder is quite distracting.

**Comment by Jax0rz** [comment]
The problem is solved in ST 4098,so I think this is a ST 4 bug.
