### ISSUE TITLE
More icon wishes

### ISSUE THREAD

**Issue by dahanbn** [Monokai/monokai-pro-sublime-text#26]
I really love your sidebar file icons: 

I really would love to have beautiful custom icons for .csv and .sql. 

That would be fantastic.

**Comment by Monokai** [comment]
Added .sql in version 1.1.1. Actually there's also a new .csv icon there, but Sublime cannot see it, because it doesn't have a special syntax for csv, and as far as I know, there aren't any Sublime packages that define a .csv syntax.

Unfortunately Sublime cannot select icons based on file extensions, so for now, the .csv icon is only visible in VSCode.

**Comment by dahanbn** [comment]
Thanks for your work. I use [Advanced CSV](https://packagecontrol.io/packages/Advanced%20CSV) and that has a tmLanguage file and provides some kind of syntax highlighting. Maybe that package and its syntax defintion can be used to define a sql icon.

By the way the table icon for csv is really looking great.

**Comment by Monokai** [comment]
I added the source selector for Advanced CSV in 1.1.2 and that seems to work. The .csv icon is now visible.
