### ISSUE TITLE
Some characters have a wrong syntax highlighting color

### ISSUE THREAD

**Issue by joaomartins33376** [Monokai/monokai-pro-sublime-text#44]
![screen shot 2017-10-16 at 01 11 23](https://user-images.githubusercontent.com/19396817/31591140-3deb0e82-b214-11e7-82ab-28325791a1da.png)
This seems to be a syntax highlighting bug. Chars like "%" in a string appears in white color as well as the first character following.

Monokai Pro version - 1.1.4
Sublime Text 3 version - 3143

**Comment by Monokai** [comment]
Yes, seems like a bug. It's important to know that syntax highlighting is different from syntax definition. Monokai Pro has syntax highlighting, but it depends on syntax definitions of a language. This is where text gets parsed into separate parts that can be highlighted. In this case the parser thinks `% c` a placeholder. The bug here probably lies somewhere in the syntax definition of the python language.
