### ISSUE TITLE
Create folder icon

### ISSUE THREAD

**Issue by atomicsaiko** [Monokai/monokai-pro-sublime-text#74]
Current Monokai Pro theme uses the old style triangle shaped bullet point. I think adding matching folder icons would greatly improve the theme visuals.

**Comment by Monokai** [comment]
It's not the standard icon, but I deliberately kept a small icon for folders, as folders are always the same type.

The reason of file icons is to quickly distinguish between different types of files that would otherwise look the same. Folders are always folders, so my reasoning was to keep this minimal so as to not distract you too much with a repetitive icon in the sidebar.

**Comment by jun1432** [comment]
Hi @Monokai,

How can we customize the folder icon? Like I want to use the folder icon instead of the triangle icon?

Just for preference. :)
