### ISSUE TITLE
Difficult to see rulers in filter spectrum variant

### ISSUE THREAD

**Issue by snim2** [Monokai/monokai-pro-sublime-text#8]
The screenshot below shows a blank file in Sublime Text 3 with the Monokai Pro Filter Spectrum theme applied. There are two rulers (at chars 80 and 120), but these are almost invisible. The other theme variants are slightly worse than this, there doesn't seem to be a variant with a background quite black enough (or rulers bright enough) for the rulers to be useful.

![blank_sublime_filter_spectrum](https://user-images.githubusercontent.com/97674/27484881-bac8f4ec-5822-11e7-8f37-bea040aadfee.png)

**Comment by Monokai** [comment]
Good one, actually haven't tested with rulers. I'll adjust this in the next update.

**Comment by snim2** [comment]
Many thanks!

**Comment by DefiantBidet** [comment]
for reference, as you already mentioned you're looking into it, this is a cropped image of 2 rulers in the octagon theme. the image should show the rulers with a little padding on either side, but they're hardly visible.

![image](https://user-images.githubusercontent.com/1092959/27525252-3135af1a-5a0a-11e7-887f-aca71efb7364.png)

great theme! thanks for the attention to detail.

**Comment by Monokai** [comment]
Turns out this is a tricky one. Sublime Text derives this color from the main foreground color, and it's also tied to the color of the invisible characters (what you see when you have `draw_white_space` set). 

In the end I tried to find a good balance between ruler visibility and invisible character invisibility. They're both a bit more prominent now, but it looks it's hard-coded that the rulers are slightly more transparent anyway.
